### ISSUE TITLE
Cannot be used in OSGi with versions of Guava newer than 15.1.

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-datatype-guava#81]
See https://github.com/FasterXML/jackson-datatype-guava/pull/80.

The version constraint in the OSGi metadata is very strict, so it demands a very particular version of Guava.

**Comment by pgelinas** [comment]
It is very strict because the Guava guys are nuts about their versioning scheme and backward compatibility. They keep things marked as [deprecated for 2 years](https://code.google.com/p/guava-libraries/wiki/PhilosophyExplained#Iteration) and they change things marked as @Beta anytime. Although this library doesn't use any @Beta-annotated API, consumer might do. 

Relaxing the constraint might open a big can o' worms, I would be extremely vigilant if you want to do this.

**Comment by cowtowncoder** [comment]
I asked about this on jackson dev list, and did not get any feedback. Since this only affects OSGi, and since one can still force particular versions, I am ok with the change for now. If problems occur we can definitely re-evaluate this question; but for now it seems to solve an existing problem.

**Comment by cowtowncoder** [comment]
I merged it as suggested, will be part of 2.5.5, 2.6.2 (2.4 branch is closed, but if a patch was released, it'd be 2.4.6-1 or 2.4.7). I hope I didn't bungle anything with merge, as version indicator changed a bit in 2.5; I don't have good test set suite.
